
trigger:
- master

pool:
  vmImage: ubuntu-default

steps:
- task: CopyFiles@2
  displayName: 'Copy json file to work directory'
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)'
    Contents: '**.json'
    TargetFolder: '$(Agent.BuildDirectory)'
    OverWrite: true

- script: 'sudo docker run -d -p 27017:27017 --name mongo-on-dcoker -e MONGO_INITDB_ROOT_USERNAME=mongoadmin -e MONGO_INITDB_ROOT_PASSWORD=$(internaldockermongodb) mongo'
  displayName: 'Docker Container with MongoDB'

- script: 'sudo apt-get install -y mongodb-org-tools'
  displayName: 'Install MongoDB tools'

- script: 'mongoimport --db test --collection inventory --authenticationDatabase admin --username mongoadmin --password $(internaldockermongodb) --file $(Agent.BuildDirectory)/Common-Currency.json'
  displayName: 'Transfer .json file into MongoDB container'

