pool:
  name: Azure Pipelines
  
steps:
- task: DownloadSecureFile@1
  displayName: 'Download secure file'
  inputs:
    secureFile: 'Common-Currency.json'
    retryCount: 2

- task: CopyFilesOverSSH@0
  displayName: 'Securely copy files to the remote machine'
  inputs:
    sshEndpoint: MongoDbconn
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'Common-Currency.json'
    targetFolder: /home/ubuadmin/

- task: SSH@0
  displayName: 'Run shell inline on remote machine'
  inputs:
    sshEndpoint: MongoDbconn
    runOptions: inline
    inline: 'mongoimport --db test --collection inventory --authenticationDatabase admin --username mongoadmin --password $(internaldockermongodb) --file /home/ubuadmin/Common-Currency.json'
    failOnStdErr: false

