pool:
  name: Azure Pipelines

steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Agent.BuildDirectory)'
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)'
    Contents: '**.json'
    TargetFolder: '$(Agent.BuildDirectory)'
    OverWrite: true

- script: 'sudo apt-get install -y mongodb-org-tools'
  displayName: 'Command Line Script'

- script: 'sudo docker run -d -p 27017:27017 --name mongo-on-dcoker -e MONGO_INITDB_ROOT_USERNAME=mongoadmin -e MONGO_INITDB_ROOT_PASSWORD=$(internaldockermongodb) mongo'
  displayName: 'Docker MongoDB install'

- script: 'mongoimport --db test --collection inventory --authenticationDatabase admin --username mongoadmin --password $(internaldockermongodb) --file $(Agent.BuildDirectory)/Common-Currency.json'
  displayName: 'Command Line Script'
